version: '3.8'

services:
  golang-kafka:
    container_name: pp_golang_kafka
    image: prontopro/golang:1.16.7-1-dev
    env_file: ./.env.dist
    command: go run cmd/golang-kafka/main.go server
    working_dir: /srv
    volumes:
      - ./:/srv:cached
    ports:
      - "8080:8080"

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
