version: '3.8'

services:
  event-stream-poc-nginx:
    container_name: event_stream_poc_nginx
    image: nginx:stable
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/event-stream-poc.conf:cached
    - ./public:/srv/public
    ports:
    - 8080:80
    networks:
      event_stream_poc:

  event-stream-poc-php-api:
    container_name: event_stream_poc_php_api
    build: .
    env_file: ./.env.dist
    working_dir: /srv
    volumes:
    - ./:/srv:cached
    networks:
      event_stream_poc:

  event-stream-poc-php-consumer:
    container_name: event_stream_poc_php_consumer
    build: .
    env_file: ./.env.dist
    working_dir: /srv
    volumes:
    - ./:/srv:cached
    networks:
      event_stream_poc:
    # entrypoint:
    # - php
    # - /srv/bin/console
    # - consumer_command_name

  zookeeper:
    container_name: event_stream_poc_zookeeper
    image: docker.io/bitnami/zookeeper:3.7
    ports:
    - 2181:2181
    volumes:
    - zookeeper_data:/bitnami
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      event_stream_poc:

  kafka:
    container_name: event_stream_poc_kafka
    image: docker.io/bitnami/kafka:3
    ports:
    - 9092:9092
    volumes:
    - kafka_data:/bitnami
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
    - zookeeper
    networks:
      event_stream_poc:

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  event_stream_poc:
    driver: bridge
