// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: internal/pkg/infrastructure/event_stream/review_rating_incremented/review_rating_incremented_event.proto

package review_rating_incremented

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewRatingIncrementedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Review *ReviewRatingIncrementedEvent_Review `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
}

func (x *ReviewRatingIncrementedEvent) Reset() {
	*x = ReviewRatingIncrementedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReviewRatingIncrementedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRatingIncrementedEvent) ProtoMessage() {}

func (x *ReviewRatingIncrementedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRatingIncrementedEvent.ProtoReflect.Descriptor instead.
func (*ReviewRatingIncrementedEvent) Descriptor() ([]byte, []int) {
	return file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewRatingIncrementedEvent) GetReview() *ReviewRatingIncrementedEvent_Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type ReviewRatingIncrementedEvent_Review struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *ReviewRatingIncrementedEvent_Review) Reset() {
	*x = ReviewRatingIncrementedEvent_Review{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReviewRatingIncrementedEvent_Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRatingIncrementedEvent_Review) ProtoMessage() {}

func (x *ReviewRatingIncrementedEvent_Review) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRatingIncrementedEvent_Review.ProtoReflect.Descriptor instead.
func (*ReviewRatingIncrementedEvent_Review) Descriptor() ([]byte, []int) {
	return file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReviewRatingIncrementedEvent_Review) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto protoreflect.FileDescriptor

var file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDesc = []byte{
	0x0a, 0x68, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x65, 0x64, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x1c, 0x52, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x06, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x52, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x52, 0x06, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x1a, 0x1c, 0x0a, 0x06, 0x52, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x42, 0x44, 0x5a, 0x42, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDescOnce sync.Once
	file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDescData = file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDesc
)

func file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDescGZIP() []byte {
	file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDescOnce.Do(func() {
		file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDescData)
	})
	return file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDescData
}

var file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_goTypes = []interface{}{
	(*ReviewRatingIncrementedEvent)(nil),        // 0: ReviewRatingIncrementedEvent
	(*ReviewRatingIncrementedEvent_Review)(nil), // 1: ReviewRatingIncrementedEvent.Review
}
var file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_depIdxs = []int32{
	1, // 0: ReviewRatingIncrementedEvent.review:type_name -> ReviewRatingIncrementedEvent.Review
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_init()
}
func file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_init() {
	if File_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReviewRatingIncrementedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReviewRatingIncrementedEvent_Review); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_goTypes,
		DependencyIndexes: file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_depIdxs,
		MessageInfos:      file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_msgTypes,
	}.Build()
	File_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto = out.File
	file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_rawDesc = nil
	file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_goTypes = nil
	file_internal_pkg_infrastructure_event_stream_review_rating_incremented_review_rating_incremented_event_proto_depIdxs = nil
}
